services:
  smardos_v2:
    build: .
    container_name: smardos_v2
    ports:
      - "7001:8501"
    volumes:
      - .:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      streamlit run home.py
      --server.address=0.0.0.0
      --server.port=8501
